name: CI
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - run: npm ci
    - run: npm test
    - name: Self-test
      if: github.event_name == 'pull_request'
      uses: ./
      with:
        allowed: pass-test
